#!/usr/bin/env bash
# PHASE 128b SPIKE — TOSSABLE. Phase 133 owns G2-REPLY productionization;
# this file is spike-only and SHOULD BE DELETED after the verdict is committed.
# Path B: claude -p --input-format stream-json --output-format stream-json (D-O1 step 1)

set -euo pipefail

EVIDENCE_DIR=".planning/spikes/128b-write-back/evidence"
SCRATCH=$(mktemp -d -t spike-128b-B-XXXXXX)
trap 'rm -rf "$SCRATCH"' EXIT

echo "[Path B probe] fresh-session stream-json round-trip ($(date -Iseconds))"

# Fresh-session probe — adapted from RESEARCH §"Path B" lines 312-314.
# Output redirected into the COMMITTED evidence dir so the artefacts survive
# the trap-cleanup of $SCRATCH and are picked up by Plan 06 MEASUREMENTS.
#
# DEVIATION FROM RESEARCH (Rule 3 — Blocking issue, auto-fixed): the claude CLI
# rejects `--output-format=stream-json` without `--verbose` ("Error: When using
# --print, --output-format=stream-json requires --verbose"). The flag was added
# upstream after RESEARCH.md was authored. Adding `--verbose` does not change
# the probe semantics — stream-json output is still emitted to stdout; verbose
# adds extra system rows to the JSONL stream which the grep -E '1337' sentinel
# check tolerates without modification. Documented in 128b-01-SUMMARY.md.
#
# `|| true` keeps the script alive even if claude returns non-zero — the
# transcript MUST be written either way (Pitfall 5: mechanical verdict, the
# transcript records FAIL just as faithfully as PASS).
mkdir -p "$EVIDENCE_DIR"
printf '%s\n' '{"type":"user","message":{"role":"user","content":"Compute seven multiplied by one hundred ninety-one. Reply with only the resulting integer."}}' \
  | claude -p --input-format stream-json --output-format stream-json --verbose --model haiku \
  > "$EVIDENCE_DIR/pathB-fresh-out.jsonl" 2> "$EVIDENCE_DIR/pathB-fresh-err.txt" \
  || true

# Sentinel check (Pitfall 1 — sentinel 1337 must NOT appear in the prompt text;
# the prompt asks the model to compute 7 * 191, which produces 1337 in the reply).
if grep -qE '1337' "$EVIDENCE_DIR/pathB-fresh-out.jsonl"; then
  FRESH_PASS=1
  echo "[Path B] fresh-session sentinel 1337 detected ⇒ step 3 ✓"
else
  FRESH_PASS=0
  echo "[Path B] fresh-session sentinel NOT detected ⇒ step 3 ✗ (unexpected — see RESEARCH §Path B Predicted verdict)"
fi

# Active-session NEGATIVE finding (do NOT attempt — document why).
echo "[Path B] active-session attempt: SKIPPED BY DESIGN."
echo "[Path B] rationale: claude --help confirms -p is single-shot (print-and-exit)."
echo "[Path B] there is no documented surface to feed stream-json into an"
echo "[Path B] already-running interactive session. Active-session step 2"
echo "[Path B] (reaches input channel) FAILS structurally, not for lack of effort."
echo "[Path B] Per CONTEXT D-V3 'unsafe primitives' clause: ptrace / proc-fd"
echo "[Path B] hacks are explicitly forbidden as PASS evidence."

# Mini-verdict computation — mechanical (Pitfall 5: no subjective override).
# The TRANSCRIPT.md is generated by this heredoc using $FRESH_PASS computed from grep above,
# NOT by hand-edit; reviewer can re-run the script and confirm the same output.
if [ "$FRESH_PASS" -eq 1 ]; then
  STEP3_FRESH="✓ (sentinel 1337 present in stream-json output)"
  FRESH_VERDICT="PASS"
  OVERALL_VERDICT="DEGRADE (fresh-only)"
else
  STEP3_FRESH="✗ (sentinel 1337 NOT present — see pathB-fresh-out.jsonl)"
  FRESH_VERDICT="FAIL"
  OVERALL_VERDICT="FAIL"
fi

CLAUDE_VERSION=$(claude --version 2>/dev/null || echo unknown)
RUN_TS=$(date -Iseconds)

cat > "$EVIDENCE_DIR/pathB-TRANSCRIPT.md" <<EOF
# Path B — Per-Path D-V1 Mini-Verdict

Probe run: ${RUN_TS}
Script: .planning/spikes/128b-write-back/pathB-stream-json.sh
claude version: ${CLAUDE_VERSION}

## D-V1 Four-Step Gate

| Step | Description | Fresh session | Active session |
|------|-------------|---------------|----------------|
| 1    | Reply originates from a non-TTY writer process | ✓ (bash heredoc piped into claude stdin) | ✗ (no input channel — \`-p\` is print-and-exit) |
| 2    | String reaches input channel | ✓ (stdin of fresh claude subprocess) | ✗ (no active-session attach surface) |
| 3    | Claude processes as next user turn | ${STEP3_FRESH} | ✗ (vacuous — no input was received) |
| 4    | Session continues healthy ≥60s | N/A (claude -p exits after single response — by design, not a failure) | ✗ (vacuous) |

## Mini-Verdict

**Fresh-session: ${FRESH_VERDICT}**
**Active-session: STRUCTURAL FAIL** (no input channel exists; not a defect of Path B but a property of \`claude -p\`).

**Per D-V2 bullet 1** ("Round-trip works ONLY on fresh \`claude -p\` sessions, NOT mid-interactive-session"):
Path B mini-verdict ⇒ **${OVERALL_VERDICT}**

## Evidence

- \`pathB-fresh-out.jsonl\` — full stream-json transcript (raw)
- \`pathB-fresh-err.txt\` — stderr (auth, permission, network errors if any)

## Cited

- CONTEXT D-V1 / D-V2 (verdict gates)
- CONTEXT D-O1 path (b) — "Likely PASSes for fresh sessions; the active-session question is whether stdin is re-readable mid-interactive (it almost certainly is NOT — \`-p\` is print-and-exit)"
- RESEARCH §"Path B" — predicted verdict DEGRADE (fresh-only) matches empirical result above
EOF

echo "[Path B] transcript written: $EVIDENCE_DIR/pathB-TRANSCRIPT.md"

exit 0
